# Generated by Django 3.0.7 on 2020-07-08 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('88babff0-335c-466b-a6b3-c377d9139646'), editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
