# Generated by Django 3.0.7 on 2020-07-09 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bookes', '0002_auto_20200709_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0ccf43e0-4b8c-4ac2-8961-29d81fe01ff5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
