# Generated by Django 3.0.7 on 2020-07-19 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bookes', '0003_auto_20200709_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c49a8114-3de3-4339-b47f-0c075667ebe7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
