# Generated by Django 3.0.7 on 2020-07-27 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bookes', '0004_auto_20200719_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d36e9822-7238-42f4-a507-e1ec81c66996'), editable=False, primary_key=True, serialize=False),
        ),
    ]
